name: Installing Npm

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./all_in_docker/client
    steps:
    - name: Set up Node.js
      uses: action/setup-node@v2
      with:
        node_version: "16"

    - name: Installing Npm
      run: npm Install
    
    - name: starting Npm
      run: npm start



